### ISSUE TITLE
[Suggestion] Please package this library on PyPi/pip

### ISSUE THREAD

**Issue by joshuaboniface** [tinue/APA102_Pi#31]
I'm currently using this library to drive [another project](https://github.com/joshuaboniface/respeaker-led), and I would love to be able to use it as an installable Python module via `pip` instead of hard-forking it into that project (thanks for being GPL!). With the APA102-containing [ReSpeaker 4-mic](https://www.seeedstudio.com/ReSpeaker-4-Mic-Array-for-Raspberry-Pi-p-2941.html) on the market this might be very helpful for other projects based on that device as well!

**Comment by tinue** [comment]
Thank you for the suggestion!
I never thought that the library will actually be used in LED projects. I originally intended it to be an educational peace to understand the workings of APA102 LEDs. That's why it is not packaged as an actual library.
Anyway, I'll have a look at `pip` when I find some time, and can hopefully produce an installable package.
P.S. First time that I heard about ReSpeaker 4-mic, looks like a cool product.

**Comment by tinue** [comment]
Could you do me a favour please: Check out the branch "latest" and see if you can install the library. It's explained in the readme how this is done.
The library is not uploaded to PyPi, but can be installed nevertheless. A hard fork is no longer necessary.
If all works fine for a while, I might go ahead and upload it.

**Comment by joshuaboniface** [comment]
Working great for me, thanks a lot!

**Comment by tinue** [comment]
Thanks for testing! I merged the branch and will close the suggestion.
