### ISSUE TITLE
A level shifter is not needed

### ISSUE THREAD

**Issue by Marlor** [tinue/APA102_Pi#32]
Just wanted to let you know, a 4.5V regulator is build in the APA102.
So if you skip the 74AHCT125/74AHC125, the first LED will act as one.

Love your library, thank you for your work.

**Comment by tinue** [comment]
Thanks for your comment!

When I wrote the guide I checked the specifications. I can't find the one I used anymore, but here is another one: https://cdn-shop.adafruit.com/datasheets/APA102.pdf.

What I understand is this:
- For a "high" signal on the data or clock line, you need at least 70% of the supply voltage (page 3, VIH).
- If the supply voltage is say 5.2V, dropped to e.g. 4.9V due to cable resistance and high current draw of the LEDs, this would be 3.43V; The 3.3V of the Raspberry Pi would be too low in this case.
- To be on the safe side, you would need to lower the supply voltage to 4.7V or lower.

Having said this, I think many APA102 do work without a level shifter, because apparently the 70% seems to be lower in practice.

The 4.5V regulator does seem to regulate the supply voltage, not the data/clock lines. Plus I think it does not boost voltage, it merely drops voltage down to 4.5V: It does say in the spec sheet that a condition for the regulator to work is that the supply voltage is at least 5V.

All in all, I think the level shifter is required after all, but you might get lucky, especially with a bad power supply that drops its voltage quickly.
